x-common-env: &common-env
  DJANGO_DEBUG: "false"
  OPENAI_API_KEY: ${OPENAI_API_KEY}

services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - backend

  redis:
    image: redis:7
    networks:
      - backend

  django:
    image: caneplayz/rptu4you-frontend:latest
    environment:
      <<: *common-env
      API_KEY: ${API_KEY}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      SERVER: django
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - redis
    command: ["python", "/app/entrypoint.py"]

  celery-worker:
    image: caneplayz/rptu4you-frontend:latest
    environment:
      <<: *common-env
    depends_on:
      - redis
    networks:
      - backend
    command: celery -A rptu4you worker --loglevel=info
    user: "1001"

  celery-beat:
    image: caneplayz/rptu4you-frontend:latest
    depends_on:
      - redis
    networks:
      - backend
    command: celery -A rptu4you beat --loglevel=info
    user: "1001"

  flower:
    image: caneplayz/rptu4you-frontend:latest
    depends_on:
      - redis
    networks:
      - backend
    command: celery -A rptu4you flower --port=5555 --address=0.0.0.0
    ports:
      - "5555:5555"
    user: "1001"

  scraper:
    image: caneplayz/rptu4you-scraper:latest
    environment:
      - API_KEY=${API_KEY}
      - IMAP_SERVER=${IMAP_SERVER}
      - IMAP_PORT=${IMAP_PORT}
      - IMAP_USERNAME=${IMAP_USERNAME}
      - IMAP_PASSWORD=${IMAP_PASSWORD}
    networks:
      - backend
    command: ["python", "/app/scheduler.py"]

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    command:
      - --http-enabled
      - --admin-password=${PORTAINER_PASSWORD_HASH}
    networks:
      - backend

networks:
  backend:

volumes:
  db_data:
  portainer_data:
