services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  django:
    image: caneplayz/rptu4you-frontend:latest
    environment:
      - API_KEY=${API_KEY}
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db
    command: /app/entrypoint.sh

  scraper:
    image: caneplayz/rptu4you-scraper:latest
    environment:
      - API_KEY=${API_KEY}
    networks:
      - backend
    depends_on:
      - db
      - django
    command: python -u scheduler.py

networks:
  backend:

volumes:
  db_data:
