name: Build and publish Docker images

on: push

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push rptu4you-frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: caneplayz/rptu4you-frontend:latest

      - name: Build and push rptu4you-scraper
        uses: docker/build-push-action@v6
        with:
          context: ./webscraper
          file: ./webscraper/Dockerfile
          push: true
          tags: caneplayz/rptu4you-scraper:latest
