# Generated by Django 5.2.7 on 2025-11-13 07:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=160, null=True, unique=True)),
                ('name', models.CharField()),
                ('name_de', models.CharField(null=True)),
                ('name_en', models.CharField(null=True)),
                ('name_es', models.CharField(null=True)),
                ('name_fr', models.CharField(null=True)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quellen',
            },
        ),
        migrations.CreateModel(
            name='InhaltsKategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_de', models.CharField(max_length=100, null=True, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_es', models.CharField(max_length=100, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Inhaltskategorien',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('titel', models.CharField()),
                ('erstellungsdatum', models.DateTimeField()),
                ('quelle_typ', models.CharField(choices=[('Fachschaft', 'Fachschaft'), ('Externe Website', 'Externe Website'), ('Sammel-Rundmail', 'Sammel-Rundmail'), ('Stellenangebote Sammel-Rundmail', 'Stellenangebote Sammel-Rundmail'), ('Rundmail', 'Rundmail'), ('Interne Website', 'Interne Website'), ('Trusted Account', 'Trusted Account')], max_length=35)),
                ('is_cleaned_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='OpenAITokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('used_tokens', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'OpenAI Token Usage',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Sprache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('name_englisch', models.CharField(max_length=30, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sprachen',
            },
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_de', models.CharField(max_length=100, null=True, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_es', models.CharField(max_length=100, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Standorte',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('titel', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Texte',
            },
        ),
        migrations.CreateModel(
            name='TrustedUserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trusted-User-Bewerbung',
                'verbose_name_plural': 'Trusted-User-Bewerbungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zielgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_de', models.CharField(max_length=100, null=True, unique=True)),
                ('name_en', models.CharField(max_length=100, null=True, unique=True)),
                ('name_es', models.CharField(max_length=100, null=True, unique=True)),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Zielgruppen',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_trusted', models.BooleanField(default=False)),
                ('include_rundmail', models.BooleanField(default=False, verbose_name='Rundmails einbeziehen')),
                ('include_sammel_rundmail', models.BooleanField(default=False, verbose_name='Sammel-Rundmails einbeziehen')),
                ('preferred_language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'Englisch'), ('es', 'Spanisch'), ('fr', 'Französisch')], default='de', max_length=5, verbose_name='Bevorzugte Sprache')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('repeat', models.CharField(choices=[('none', 'Keine'), ('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('yearly', 'Jährlich')], default='none', max_length=10)),
                ('repeat_until', models.DateTimeField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Kalendereinträge',
            },
        ),
        migrations.CreateModel(
            name='EmailVerteiler',
            fields=[
                ('quelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.quelle')),
            ],
            options={
                'verbose_name_plural': 'Email-Verteiler',
            },
            bases=('news.quelle',),
        ),
        migrations.CreateModel(
            name='ExterneWebsite',
            fields=[
                ('quelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.quelle')),
            ],
            options={
                'verbose_name_plural': 'Externe Websites',
            },
            bases=('news.quelle',),
        ),
        migrations.CreateModel(
            name='Fachschaft',
            fields=[
                ('quelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.quelle')),
            ],
            options={
                'verbose_name_plural': 'Fachschaften',
            },
            bases=('news.quelle',),
        ),
        migrations.CreateModel(
            name='InterneWebsite',
            fields=[
                ('quelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.quelle')),
            ],
            options={
                'verbose_name_plural': 'Interne Websites',
            },
            bases=('news.quelle',),
        ),
        migrations.CreateModel(
            name='Rundmail',
            fields=[
                ('quelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.quelle')),
                ('rundmail_id', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Rundmails',
            },
            bases=('news.quelle',),
        ),
        migrations.CreateModel(
            name='TrustedAccountQuelle',
            fields=[
                ('quelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.quelle')),
            ],
            options={
                'verbose_name_plural': 'Trusted Accounts',
            },
            bases=('news.quelle',),
        ),
        migrations.AddConstraint(
            model_name='quelle',
            constraint=models.UniqueConstraint(fields=('name', 'url'), name='unique_quelle_name_url'),
        ),
        migrations.AddConstraint(
            model_name='quelle',
            constraint=models.UniqueConstraint(fields=('name_de', 'url'), name='unique_quelle_name_url-name_de'),
        ),
        migrations.AddConstraint(
            model_name='quelle',
            constraint=models.UniqueConstraint(fields=('name_en', 'url'), name='unique_quelle_name_url-name_en'),
        ),
        migrations.AddConstraint(
            model_name='quelle',
            constraint=models.UniqueConstraint(fields=('name_es', 'url'), name='unique_quelle_name_url-name_es'),
        ),
        migrations.AddConstraint(
            model_name='quelle',
            constraint=models.UniqueConstraint(fields=('name_fr', 'url'), name='unique_quelle_name_url-name_fr'),
        ),
        migrations.AddField(
            model_name='user',
            name='quellen',
            field=models.ManyToManyField(blank=True, to='news.quelle'),
        ),
        migrations.AddField(
            model_name='user',
            name='inhaltskategorien',
            field=models.ManyToManyField(blank=True, to='news.inhaltskategorie'),
        ),
        migrations.AddField(
            model_name='news',
            name='inhaltskategorien',
            field=models.ManyToManyField(blank=True, to='news.inhaltskategorie'),
        ),
        migrations.AddField(
            model_name='news',
            name='quelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.quelle'),
        ),
        migrations.AddField(
            model_name='news',
            name='standorte',
            field=models.ManyToManyField(blank=True, to='news.standort'),
        ),
        migrations.AddField(
            model_name='user',
            name='standorte',
            field=models.ManyToManyField(blank=True, to='news.standort'),
        ),
        migrations.AddField(
            model_name='text',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texte', to='news.news'),
        ),
        migrations.AddField(
            model_name='text',
            name='sprache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.sprache'),
        ),
        migrations.AddField(
            model_name='trusteduserapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='zielgruppen',
            field=models.ManyToManyField(blank=True, to='news.zielgruppe'),
        ),
        migrations.AddField(
            model_name='user',
            name='zielgruppen',
            field=models.ManyToManyField(blank=True, to='news.zielgruppe'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.UniqueConstraint(fields=('news', 'sprache'), name='unique_news_sprache'),
        ),
        migrations.AddConstraint(
            model_name='news',
            constraint=models.UniqueConstraint(fields=('titel', 'erstellungsdatum'), name='unique_news_titel_erstellungsdatum'),
        ),
    ]
