# Generated by Django 5.2.7 on 2025-11-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inhaltskategorie',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='slug',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='standort',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='zielgruppe',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
