# Generated by Django 5.2 on 2025-04-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_text_titel_alter_sprache_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="titel",
            field=models.CharField(default="", max_length=255),
        ),
    ]
