# Generated by Django 5.2 on 2025-04-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_text_titel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="titel",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sprache",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="rolle",
            field=models.CharField(
                blank=True,
                choices=[("Student", "Student"), ("Angestellter", "Angestellter")],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="news",
            constraint=models.UniqueConstraint(
                fields=("titel", "erstellungsdatum"),
                name="unique_news_titel_erstellungsdatum",
            ),
        ),
        migrations.AddConstraint(
            model_name="text",
            constraint=models.UniqueConstraint(
                fields=("news", "sprache"), name="unique_news_sprache"
            ),
        ),
    ]
