# Generated by Django 5.2 on 2025-04-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_news_titel_alter_sprache_code_alter_user_rolle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zielgruppe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Zielgruppen",
            },
        ),
        migrations.RenameModel(
            old_name="Kategorie",
            new_name="InhaltsKategorie",
        ),
        migrations.RemoveField(
            model_name="user",
            name="rolle",
        ),
        migrations.AlterField(
            model_name="text",
            name="sprache",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="news.sprache"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="zielgruppe",
            field=models.ManyToManyField(blank=True, to="news.zielgruppe"),
        ),
        migrations.AddField(
            model_name="user",
            name="zielgruppe",
            field=models.ManyToManyField(blank=True, to="news.zielgruppe"),
        ),
    ]
