# Generated by Django 5.2.3 on 2025-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_alter_calendarevent_title_alter_news_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAITokenUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("used_tokens", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
