# Generated by Django 5.2.3 on 2025-07-02 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0010_alter_inhaltskategorie_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerteiler",
            fields=[
                (
                    "quelle_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="news.quelle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Email-Verteiler",
            },
            bases=("news.quelle",),
        ),
    ]
