# Generated by Django 5.2.4 on 2025-07-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_emailverteiler"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="group",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="repeat",
            field=models.CharField(
                choices=[
                    ("none", "Keine"),
                    ("daily", "Täglich"),
                    ("weekly", "Wöchentlich"),
                    ("monthly", "Monatlich"),
                    ("yearly", "Jährlich"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="repeat_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="news",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
