# Generated by Django 5.2.4 on 2025-07-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0012_calendarevent_group_calendarevent_repeat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_cleaned_up",
            field=models.BooleanField(default=False),
        ),
    ]
