# Generated by Django 5.2.4 on 2025-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0013_news_is_cleaned_up"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sprache",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
