# Generated by Django 5.2.4 on 2025-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_alter_sprache_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sprache",
            name="name_englisch",
            field=models.CharField(default="Test", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
