# Generated by Django 5.2.4 on 2025-07-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0016_news_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="kategorien",
            new_name="inhaltskategorien",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="präferenzen",
            new_name="inhaltskategorien",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="zielgruppe",
            new_name="zielgruppen",
        ),
        migrations.RemoveField(
            model_name="user",
            name="fachschaften",
        ),
        migrations.AddField(
            model_name="user",
            name="quellen",
            field=models.ManyToManyField(blank=True, to="news.fachschaft"),
        ),
        migrations.AlterField(
            model_name="quelle",
            name="name",
            field=models.CharField(),
        ),
        migrations.AddConstraint(
            model_name="quelle",
            constraint=models.UniqueConstraint(
                fields=("name", "url"), name="unique_quelle_name_url"
            ),
        ),
    ]
