# Generated by Django 5.2.4 on 2025-07-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0017_rename_kategorien_news_inhaltskategorien_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="quellen",
            field=models.ManyToManyField(blank=True, to="news.quelle"),
        ),
    ]
