# Generated by Django 5.2.4 on 2025-07-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0018_alter_user_quellen"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="zielgruppe",
            new_name="zielgruppen",
        ),
    ]
