# Generated by Django 5.2.4 on 2025-10-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0019_rename_zielgruppe_news_zielgruppen"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="include_rundmail",
            field=models.BooleanField(
                default=False, verbose_name="Rundmail einbeziehen"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="include_sammel_rundmail",
            field=models.BooleanField(
                default=False, verbose_name="Sammel-Rundmail einbeziehen"
            ),
        ),
    ]
