# Generated by Django 5.2.7 on 2025-11-05 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_user_include_rundmail_user_include_sammel_rundmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='quelle_typ',
            field=models.CharField(choices=[('Fachschaft', 'Fachschaft'), ('Externe Website', 'Externe Website'), ('Sammel-Rundmail', 'Sammel-Rundmail'), ('Stellenangebote Sammel-Rundmail', 'Stellenangebote Sammel-Rundmail'), ('Rundmail', 'Rundmail'), ('Interne Website', 'Interne Website'), ('Trusted Account', 'Trusted Account')], max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='include_rundmail',
            field=models.BooleanField(default=False, verbose_name='Rundmails einbeziehen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='include_sammel_rundmail',
            field=models.BooleanField(default=False, verbose_name='Sammel-Rundmails einbeziehen'),
        ),
        migrations.CreateModel(
            name='TrustedUserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('declined', 'Abgelehnt')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trusted-User-Bewerbung',
                'verbose_name_plural': 'Trusted-User-Bewerbungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
