# Generated by Django 5.2.7 on 2025-11-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_user_is_trusted_alter_news_quelle_typ_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='quelle',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
