# Generated by Django 5.2.7 on 2025-11-07 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_news_link_alter_quelle_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedAccountQuelle',
            fields=[
                ('quelle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.quelle')),
            ],
            options={
                'verbose_name_plural': 'Trusted Accounts',
            },
            bases=('news.quelle',),
        ),
    ]
