# Generated by Django 5.2.7 on 2025-11-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_trustedaccountquelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'Englisch'), ('es', 'Spanisch'), ('fr', 'Französisch')], default='de', max_length=5, verbose_name='Bevorzugte Sprache'),
        ),
    ]
