# Generated by Django 5.1.3 on 2025-07-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
