# Generated by Django 5.2 on 2025-04-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="titel",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sprache",
            name="code",
            field=models.CharField(default="de", max_length=5),
            preserve_default=False,
        ),
    ]
