# Generated by Django 5.2 on 2025-04-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sprache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "verbose_name_plural": "Sprachen",
            },
        ),
        migrations.RemoveField(
            model_name="news",
            name="text",
        ),
        migrations.CreateModel(
            name="Texte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texte",
                        to="news.news",
                    ),
                ),
                (
                    "sprache",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.sprache"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Texte",
            },
        ),
    ]
