# Generated by Django 5.2 on 2025-04-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_sprache_remove_news_text_texte"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Texte",
            new_name="Text",
        ),
        migrations.AddField(
            model_name="sprache",
            name="code",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
