# Generated by Django 5.2.3 on 2025-06-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_alter_news_titel_alter_text_titel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="title",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(max_length=1000),
        ),
    ]
