# Generated by Django 5.2.3 on 2025-06-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_openaitokenusage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inhaltskategorie",
            options={"verbose_name_plural": "Inhaltskategorien"},
        ),
        migrations.AlterModelOptions(
            name="openaitokenusage",
            options={
                "ordering": ["-date"],
                "verbose_name_plural": "OpenAI Token Usage",
            },
        ),
    ]
